import { CompanyRole } from "@finos/database";

export const ROLE_PERMISSIONS: Record<CompanyRole, string[]> = {
  OWNER: ["*"],
  MANAGER: [
    "company.read",
    "company.update",
    "customer.read",
    "customer.create",
    "customer.update",
    "customer.delete",
    "product.read",
    "product.create",
    "product.update",
    "inventory.read",
    "inventory.adjust",
    "sales.read",
    "sales.create",
    "sales.update",
    "sales.post",
    "payment.read",
    "payment.create",
    "banking.read",
    "banking.create",
    "banking.import",
    "banking.reconcile",
    "collections.read",
    "collections.create",
    "collections.update",
    "credit.read",
    "credit.score",
    "notification.read",
    "notification.manage",
    "ai-cfo.ask",
    "accounting.report.read",
    "rbac.members.read"
  ],
  ACCOUNTANT: [
    "company.read",
    "customer.read",
    "customer.update",
    "product.read",
    "inventory.read",
    "sales.read",
    "sales.create",
    "sales.post",
    "payment.read",
    "payment.create",
    "banking.read",
    "banking.create",
    "banking.import",
    "banking.reconcile",
    "collections.read",
    "collections.create",
    "collections.update",
    "credit.read",
    "credit.score",
    "notification.read",
    "notification.manage",
    "ai-cfo.ask",
    "accounting.report.read"
  ],
  SALES_EXECUTIVE: [
    "company.read",
    "customer.read",
    "customer.create",
    "customer.update",
    "product.read",
    "inventory.read",
    "sales.read",
    "sales.create",
    "sales.update",
    "payment.read",
    "collections.read",
    "collections.create",
    "collections.update",
    "credit.read",
    "notification.read",
    "ai-cfo.ask"
  ],
  INVENTORY_MANAGER: [
    "company.read",
    "customer.read",
    "product.read",
    "product.create",
    "product.update",
    "inventory.read",
    "inventory.adjust"
  ]
};

export function hasPermission(permissions: string[], required: string) {
  return permissions.includes("*") || permissions.includes(required);
}
